version: "3.8"

services:
  server:
    build: .
    container_name: server
    restart: unless-stopped
    volumes:
      - ./server:/app
      - logs:/var/log
    ports:
      - "8000:8000"
    env_file:
      - ".env"
    depends_on:
      - redis
      - db
    networks:
      - chat-network
  redis:
    image: redis:7.0-alpine
    container_name: redis
    networks:
      - chat-network
  db:
    image: docker.io/postgres:15.1-alpine
    container_name: db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data/
    ports:
      - "5400:5432"
    networks:
      - chat-network

volumes:
  db:
  logs:

networks:
  chat-network:
    driver: bridge
