version: "3.8"

services:
  server:
    build: .
    container_name: server
    restart: unless-stopped
    volumes:
      - ./server:/app
      - atlas-logs:/var/log
    ports:
      - "9500:8000"
    env_file:
      - ".env"
    depends_on:
      - atlas-redis
      - atlas-db
    networks:
      - atlas-network
  atlas-redis:
    image: redis:7.0-alpine
    container_name: atlas-redis
    networks:
      - atlas-network
  atlas-db:
    image: docker.io/postgres:15.1-alpine
    container_name: atlas-db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - atlas-db:/var/lib/postgresql/data/
    ports:
      - "5401:5432"
    networks:
      - atlas-network

volumes:
  atlas-db:
  atlas-logs:

networks:
  atlas-network:
    driver: bridge
